name: CI

on:
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  test-dev:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.1-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Set environment
        env:
          ENV: 'dev'
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          echo "ENV=${ENV}" >> $GITHUB_ENV
          if [ -n "${BASIC_AUTH_USERNAME}" ]; then echo "BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}" >> $GITHUB_ENV; fi
          if [ -n "${BASIC_AUTH_PASSWORD}" ]; then echo "BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}" >> $GITHUB_ENV; fi

      - name: Run tests on DEV
        run: npm test || echo "Tests completed with failures"

      - name: Prepare DEV Cucumber report for upload
        if: always()
        run: |
          mkdir -p reports/dev
          echo "Checking for Cucumber reports..."
          ls -la *.html 2>/dev/null || echo "No HTML files found"
          ls -la cucumber-report/ 2>/dev/null || echo "No cucumber-report directory found"
          
          if [ -f "cucumber-report.html" ]; then
            echo "Moving cucumber-report.html to DEV directory"
            mv cucumber-report.html reports/dev/index.html
          elif [ -d "cucumber-report" ] && [ -f "cucumber-report/index.html" ]; then
            echo "Moving cucumber-report directory to DEV"
            mv cucumber-report/* reports/dev/ 2>/dev/null || true
          elif [ -d "reports" ] && [ -f "reports/index.html" ]; then
            echo "Moving existing reports to DEV"
            mv reports/index.html reports/dev/index.html 2>/dev/null || true
          else
            echo "Creating fallback DEV report"
            echo "<html><body><h1>DEV Environment - Test Results</h1><p>Tests completed. Check the CI logs for detailed results.</p><p>If you're seeing this, the HTML report may not have been generated properly.</p></body></html>" > reports/dev/index.html
          fi
          
          echo "Final DEV report contents:"
          ls -la reports/dev/

      - name: Upload DEV Cucumber report to Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/dev
          name: dev-report

  test-stg:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.1-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Set environment
        env:
          ENV: 'stg'
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          echo "ENV=${ENV}" >> $GITHUB_ENV
          if [ -n "${BASIC_AUTH_USERNAME}" ]; then echo "BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}" >> $GITHUB_ENV; fi
          if [ -n "${BASIC_AUTH_PASSWORD}" ]; then echo "BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}" >> $GITHUB_ENV; fi

      - name: Run tests on STG
        run: npm test || echo "Tests completed with failures"

      - name: Prepare STG Cucumber report for upload
        if: always()
        run: |
          mkdir -p reports/stg
          echo "Checking for Cucumber reports..."
          ls -la *.html 2>/dev/null || echo "No HTML files found"
          ls -la cucumber-report/ 2>/dev/null || echo "No cucumber-report directory found"
          
          if [ -f "cucumber-report.html" ]; then
            echo "Moving cucumber-report.html to STG directory"
            mv cucumber-report.html reports/stg/index.html
          elif [ -d "cucumber-report" ] && [ -f "cucumber-report/index.html" ]; then
            echo "Moving cucumber-report directory to STG"
            mv cucumber-report/* reports/stg/ 2>/dev/null || true
          elif [ -d "reports" ] && [ -f "reports/index.html" ]; then
            echo "Moving existing reports to STG"
            mv reports/index.html reports/stg/index.html 2>/dev/null || true
          else
            echo "Creating fallback STG report"
            echo "<html><body><h1>STG Environment - Test Results</h1><p>Tests completed. Check the CI logs for detailed results.</p><p>If you're seeing this, the HTML report may not have been generated properly.</p></body></html>" > reports/stg/index.html
          fi
          
          echo "Final STG report contents:"
          ls -la reports/stg/

      - name: Upload STG Cucumber report to Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/stg
          name: stg-report

  deploy:
    needs: [test-dev, test-stg]
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4