name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      # Browsers and system deps are preinstalled in the container image

      - name: Set up environment
        env:
          TEST_ENV: ${{ vars.TEST_ENV || 'dev' }}
        run: |
          echo "TEST_ENV=${TEST_ENV}" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

      - name: Prepare HTML report for GitHub Pages
        if: always()
        run: |
          # Ensure index exists to avoid empty publish
          test -f playwright-report/index.html

      - name: Upload HTML report as Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Upload test-results (screenshots/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          if-no-files-found: warn

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
