name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.1-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: |
          curl -o allure-2.24.0.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxf allure-2.24.0.tgz -C /opt/
          ln -s /opt/allure-2.24.0/bin/allure /usr/local/bin/allure

      - name: Set environment
        env:
          ENV: ${{ vars.ENV || 'dev' }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          echo "ENV=${ENV}" >> $GITHUB_ENV
          if [ -n "${BASIC_AUTH_USERNAME}" ]; then echo "BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}" >> $GITHUB_ENV; fi
          if [ -n "${BASIC_AUTH_PASSWORD}" ]; then echo "BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}" >> $GITHUB_ENV; fi

      - name: Run tests
        run: npm test

      - name: Generate Allure Report
        if: always()
        run: |
          echo "Checking allure-results directory:"
          ls -la allure-results/ || echo "allure-results directory not found"
          echo "Generating Allure report..."
          allure generate allure-results --clean -o allure-report
          echo "Checking generated report:"
          ls -la allure-report/ || echo "allure-report directory not found"

      - name: Prepare Allure report for upload
        if: always()
        run: |
          if [ -d "allure-report" ]; then
            echo "Allure report directory exists, proceeding with upload"
          else
            echo "Allure report directory not found, creating empty report"
            mkdir -p allure-report
            echo "<html><body><h1>No test results available</h1></body></html>" > allure-report/index.html
          fi

      - name: Upload Allure report to Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-results
            allure-results
          if-no-files-found: warn

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4