name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
<<<<<<< HEAD
  test:
=======
  tests:
>>>>>>> origin/develop
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.55.1-jammy

    steps:
<<<<<<< HEAD
      - name: Checkout
=======
      - name: Checkout repository
>>>>>>> origin/develop
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

<<<<<<< HEAD
      - name: Set environment
        env:
          ENV: ${{ vars.ENV || 'dev' }}
=======
      # Browsers and system deps are preinstalled in the container image

      - name: Set up environment
        env:
          ENV: ${{ vars.ENV || 'prod' }}
>>>>>>> origin/develop
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          echo "ENV=${ENV}" >> $GITHUB_ENV
          if [ -n "${BASIC_AUTH_USERNAME}" ]; then echo "BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}" >> $GITHUB_ENV; fi
          if [ -n "${BASIC_AUTH_PASSWORD}" ]; then echo "BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}" >> $GITHUB_ENV; fi

      - name: Run tests
        run: npm test

<<<<<<< HEAD
      - name: Prepare Cucumber report for upload
        if: always()
        run: |
          # Create cucumber-report directory for GitHub Pages
          rm -f cucumber-report  # Remove file if it exists
          mkdir -p cucumber-report
          
          if [ -f "cucumber-report.html" ]; then
            echo "Moving cucumber-report.html to directory"
            mv cucumber-report.html cucumber-report/index.html
          elif [ -d "cucumber-report" ] && [ -f "cucumber-report/index.html" ]; then
            echo "Cucumber report directory with index.html already exists"
          else
            echo "Creating empty Cucumber report"
            echo "<html><body><h1>No test results available</h1><p>Tests may have failed or no report was generated.</p></body></html>" > cucumber-report/index.html
          fi

      - name: Upload Cucumber report to Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: cucumber-report

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
=======
      - name: Prepare HTML report for GitHub Pages
        if: always()
        run: |
          # Ensure index exists to avoid empty publish
          test -f playwright-report/index.html

      - name: Upload HTML report as Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Upload test-results (screenshots/videos)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
>>>>>>> origin/develop
          path: test-results
          if-no-files-found: warn

  deploy:
<<<<<<< HEAD
    needs: test
=======
    needs: tests
>>>>>>> origin/develop
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> origin/develop
